using Overseer.AI;
using Overseer.Domain;
using Overseer.Simulation;

namespace Overseer.Web.Services;

/// <summary>
/// The server runtime: crew are generated by the AI crew generator and minds
/// decide through Ollama. Everything else is the shared <see cref="StationSession"/>.
/// </summary>
public sealed class GameSession(
    IAiDecisionService aiDecisionService,
    IAiCrewGenerator crewGenerator,
    IOverseerMessageInterpreter messageInterpreter)
    : StationSession(messageInterpreter, FacilitySeeder.CreateDefault())
{
    private readonly IAiDecisionService _aiDecisionService = aiDecisionService;
    private readonly IAiCrewGenerator _crewGenerator = crewGenerator;
    private readonly NavigationSystem _navigation = new();

    private int _mindCursor;
    private bool _initialized;

    public override async Task InitializeAsync(
        CancellationToken cancellationToken = default)
    {
        if (_initialized)
        {
            return;
        }

        var scenario = ScenarioCatalog.SecureContinuity;
        var (crew, robots) = await CreateCrewForScenarioAsync(scenario, cancellationToken);
        State = FacilitySeeder.CreateDefault(
            crew,
            stationConstraints: RosterCompositionRules.ConstraintsFor(scenario, crew.Count),
            robotCount: robots);
        _initialized = true;
    }

    private async Task<(IReadOnlyList<Npc> Crew, int RobotCount)> CreateCrewForScenarioAsync(
        ScenarioDefinition scenario,
        CancellationToken cancellationToken)
    {
        // A fresh roster's crew and robot counts come from the uniform roster
        // contract. A continuing campaign keeps its surviving crew, but every
        // new station still gets its own robot count.
        var composition = RosterCompositionRules.Sample(Random.Shared.Next());
        var continuingCrew = CampaignProgressionSystem.CreateCrewForScenario(Campaign, scenario);

        IReadOnlyList<Npc> baseCrew;
        if (continuingCrew is not null)
        {
            baseCrew = continuingCrew;
        }
        else
        {
            var generated = await _crewGenerator.GenerateAsync(cancellationToken);
            baseCrew = CrewRosterScalingSystem.FitToSize(
                generated,
                scenario.Id,
                composition.CrewCount);
        }

        return (PrisonerRosterSystem.Compose(baseCrew, scenario), composition.RobotCount);
    }

    public override async Task ResetAsync(
        CancellationToken cancellationToken = default)
    {
        PauseClock();
        _mindCursor = 0;
        Campaign = new CampaignState();
        var scenario = ScenarioCatalog.SecureContinuity;
        var (crew, robots) = await CreateCrewForScenarioAsync(scenario, cancellationToken);
        State = FacilitySeeder.CreateDefault(
            crew,
            stationConstraints: RosterCompositionRules.ConstraintsFor(scenario, crew.Count),
            robotCount: robots);
        _initialized = true;
    }

    public override async Task RegenerateStationAsync(
        int? seed = null,
        CancellationToken cancellationToken = default)
    {
        PauseClock();
        _mindCursor = 0;

        var scenario = State.Scenario ?? ScenarioCatalog.SecureContinuity;
        var (crew, robots) = await CreateCrewForScenarioAsync(scenario, cancellationToken);
        State = FacilitySeeder.CreateDefault(
            crew,
            stationSeed: seed,
            stationConstraints: RosterCompositionRules.ConstraintsFor(scenario, crew.Count),
            robotCount: robots);
        ScenarioCatalog.Apply(State, scenario);
        CampaignProgressionSystem.ApplyCarryOver(Campaign, State);
        Campaign.CurrentScenarioId = scenario.Id;
        _initialized = true;
    }

    public override async Task RestoreCampaignAsync(
        CampaignState campaign,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(campaign);

        PauseClock();
        _mindCursor = 0;

        if (!CampaignProgressionSystem.CanAutoRestoreCampaign(campaign))
        {
            Campaign = new CampaignState();
            var freshScenario = ScenarioCatalog.SecureContinuity;
            var (freshCrew, freshRobots) = await CreateCrewForScenarioAsync(freshScenario, cancellationToken);
            State = FacilitySeeder.CreateDefault(
                freshCrew,
                stationConstraints: RosterCompositionRules.ConstraintsFor(freshScenario, freshCrew.Count),
                robotCount: freshRobots);
            State.EventLog.Insert(
                0,
                "T+00:00: Previous campaign could not continue because no living crew remained; a fresh assignment was started.");
            _initialized = true;
            return;
        }

        Campaign = campaign;

        var next = CampaignProgressionSystem.NextScenario(Campaign);
        var last = Campaign.MissionHistory.LastOrDefault();
        var scenario = next
            ?? (last is null ? null : ScenarioCatalog.Find(last.ScenarioId))
            ?? throw new InvalidOperationException(
                "Campaign state does not identify a valid scenario roster policy.");

        var (crew, robots) = await CreateCrewForScenarioAsync(scenario, cancellationToken);
        State = FacilitySeeder.CreateDefault(
            crew,
            stationConstraints: RosterCompositionRules.ConstraintsFor(scenario, crew.Count),
            robotCount: robots);
        ScenarioCatalog.Apply(State, scenario);

        if (next is null)
        {
            State.ScenarioStatus = last?.Outcome ?? ScenarioStatus.Won;
            State.ScenarioOutcome = Campaign.Ending?.Summary
                ?? "All campaign assignments are recorded. Awaiting final Overseer decision.";
        }

        CampaignProgressionSystem.ApplyCarryOver(Campaign, State);
        Campaign.CurrentScenarioId = scenario.Id;
        _initialized = true;
    }

    /// <summary>
    /// Starts only the next unlocked campaign assignment on a fresh station.
    /// Arbitrary scenario selection is intentionally rejected by the campaign
    /// layer instead of relying on UI controls for progression integrity.
    /// </summary>
    public override async Task LoadScenarioAsync(
        string scenarioId,
        CancellationToken cancellationToken = default)
    {
        PauseClock();
        _mindCursor = 0;
        CampaignProgressionSystem.CaptureCompletedMission(Campaign, State);

        if (!CampaignProgressionSystem.CanStartScenario(Campaign, scenarioId))
        {
            Log($"DIRECTIVE PACKAGE {scenarioId} is locked by campaign progression.");
            return;
        }

        var scenario = ScenarioCatalog.Find(scenarioId);
        if (scenario is null)
        {
            return;
        }

        var (crew, robots) = await CreateCrewForScenarioAsync(scenario, cancellationToken);
        State = FacilitySeeder.CreateDefault(
            crew,
            stationConstraints: RosterCompositionRules.ConstraintsFor(scenario, crew.Count),
            robotCount: robots);
        ScenarioCatalog.Apply(State, scenario);
        CampaignProgressionSystem.ApplyCarryOver(Campaign, State);
        Campaign.CurrentScenarioId = scenario.Id;
        _initialized = true;

        Log($"DIRECTIVE PACKAGE LOADED — {scenario.Title}.");
    }

    /// <inheritdoc />
    public override async Task LoadStandaloneScenarioAsync(
        string scenarioId,
        CancellationToken cancellationToken = default)
    {
        PauseClock();
        _mindCursor = 0;

        var scenario = ScenarioCatalog.StandaloneAssignments.FirstOrDefault(candidate =>
            candidate.Id.Equals(scenarioId, StringComparison.OrdinalIgnoreCase));

        if (scenario is null)
        {
            Log($"SPECIAL ASSIGNMENT {scenarioId} is not a recognised standalone package.");
            return;
        }

        var (crew, robots) = await CreateCrewForScenarioAsync(scenario, cancellationToken);
        State = FacilitySeeder.CreateDefault(
            crew,
            stationConstraints: RosterCompositionRules.ConstraintsFor(scenario, crew.Count),
            robotCount: robots);
        ScenarioCatalog.Apply(State, scenario);
        _initialized = true;

        Log($"SPECIAL ASSIGNMENT LOADED — {scenario.Title}.");
    }

    protected override Task ThinkAsync(CancellationToken cancellationToken) =>
        ThinkIfDueAsync(cancellationToken);

    private async Task ThinkIfDueAsync(CancellationToken cancellationToken)
    {
        var living = State.Crew
            .Where(npc =>
                npc.IsAlive
                && !npc.IsContainmentBreachInProgress)
            .OrderBy(npc => npc.Name)
            .ToList();

        if (living.Count == 0)
        {
            return;
        }

        // Environmental danger is allowed to interrupt the normal cognition
        // cadence. C# still does not choose the goal: it only asks the mind to
        // reconsider immediately instead of leaving somebody committed to a
        // 24-minute-old routine while their compartment becomes unsafe.
        // A compartment draining toward a breach through an open hatch beside
        // this person counts too, before its pressure crosses the danger line.
        var vacuumDepths = EnvironmentSystem.FindVacuumDepths(State);
        var emergencyNpc = living
            .Where(npc =>
            {
                var room = State.Facility.Rooms[npc.CurrentRoomId];

                if (npc.IsPresent
                    && vacuumDepths.Count > 0
                    && DecompressionContainmentRules.FindHatchTowardBreach(
                        State,
                        npc,
                        vacuumDepths) is { } hatch)
                {
                    // Ollama may weigh the open hatch and choose something
                    // else; respect a fresh decision instead of re-asking
                    // every tick until it says CloseDoor.
                    var decidedRecently = npc.Intent is { Urgency: >= 85 }
                        && State.Elapsed - npc.LastThoughtAt < TimeSpan.FromMinutes(2);

                    return !DecompressionContainmentRules.IsAlreadyClosing(npc, hatch)
                        && !decidedRecently;
                }

                return CrewEnvironmentSafety.IsDangerous(room)
                    && !IsAlreadyEscapingToSaferRoom(npc, room);
            })
            .OrderByDescending(npc =>
                CrewEnvironmentSafety.RiskScore(
                    State.Facility.Rooms[npc.CurrentRoomId]))
            .ThenBy(npc => npc.Name)
            .FirstOrDefault();

        if (emergencyNpc is not null)
        {
            emergencyNpc.Intent = null;
            emergencyNpc.Movement = null;
            emergencyNpc.RoutineUntil = TimeSpan.Zero;

            await ThinkForNpcAsync(
                emergencyNpc,
                emergency: true,
                cancellationToken);

            return;
        }

        var eventNpc = living
            .Where(npc =>
                npc.NeedsMindReconsideration
                && (npc.Intent is null
                    || npc.Intent.Urgency < 85
                    || npc.Hunger >= 72
                    || npc.Fatigue >= 86))
            .OrderByDescending(npc =>
                npc.MissingPersonConcerns.Values.Any(concern =>
                    concern.Stage == MissingPersonConcernStage.Escalated))
            .ThenBy(npc => npc.Name)
            .FirstOrDefault();

        if (eventNpc is not null)
        {
            eventNpc.Intent = null;
            eventNpc.Movement = null;
            eventNpc.RoutineUntil = TimeSpan.Zero;

            await ThinkForNpcAsync(
                eventNpc,
                emergency: eventNpc.MissingPersonConcerns.Count > 0,
                cancellationToken);

            eventNpc.NeedsMindReconsideration = false;
            return;
        }

        var minute = (int)Math.Floor(State.Elapsed.TotalMinutes);

        // One ordinary mind every four simulated minutes. Emergency danger
        // bypasses this cadence above.
        if (minute <= 0 || minute % 4 != 0)
        {
            return;
        }

        var npc = living[_mindCursor % living.Count];
        _mindCursor++;

        // Do not let a routine model call erase a goal that the human is already
        // physically pursuing (including mutually coordinated social routines).
        if (npc.Intent is not null)
        {
            return;
        }

        await ThinkForNpcAsync(
            npc,
            emergency: false,
            cancellationToken);
    }

    private async Task ThinkForNpcAsync(
        Npc npc,
        bool emergency,
        CancellationToken cancellationToken)
    {
        var intent = await _aiDecisionService.DecideAsync(
            npc,
            State,
            cancellationToken);

        npc.Intent = intent;
        npc.MindMode = intent.Source;
        npc.LastThought = intent.Reason;
        npc.LastThoughtAt = State.Elapsed;
        // Owner idea #85: an in-character line from cognition, when given,
        // replaces the functional goal in the bubble; the goal still drives
        // everything else.
        npc.Bubble = new NpcBubble(
            intent.BubbleText ?? intent.Goal,
            emergency ? NpcBubbleKind.Alert : NpcBubbleKind.Thought,
            State.Elapsed,
            State.Elapsed + TimeSpan.FromMinutes(emergency ? 4 : 3));

        AudioCueSystem.Emit(
            State,
            emergency ? AudioCueKind.Warning : AudioCueKind.Thought,
            npc.Id.ToString(),
            npc.CurrentRoomId);

        // A note of one's own plan is low-value context; at urgency-scaled
        // importance it crowded real experiences out of the prompt.
        npc.Memories.Add(new Memory(
            $"I decided to: {intent.Goal}",
            State.Elapsed,
            0.25));

        Log(
            $"{npc.Name} forms an intention [{intent.Source}]: {intent.Goal}");
    }

    private bool IsAlreadyEscapingToSaferRoom(Npc npc, Room currentRoom)
    {
        if (npc.Intent is { Action: ActionKind.ForceDoor }
            && npc.CurrentAction.Kind == ActionKind.ForceDoor)
        {
            return true;
        }

        if (npc.Intent is not { Action: ActionKind.Move, TargetId: { } targetId }
            || !State.Facility.Rooms.TryGetValue(targetId, out var targetRoom))
        {
            return false;
        }

        if (CrewEnvironmentSafety.RiskScore(targetRoom)
            >= CrewEnvironmentSafety.RiskScore(currentRoom))
        {
            return false;
        }

        return _navigation.FindPathForCrew(
            State,
            npc,
            currentRoom.Id,
            targetRoom.Id).Count >= 2;
    }
}
