using Overseer.AI;
using Overseer.Domain;
using Overseer.Simulation;

namespace Overseer.Web.Services;

/// <summary>
/// The server runtime: crew are generated by the AI crew generator and minds
/// decide through Ollama. Everything else is the shared <see cref="StationSession"/>.
/// </summary>
public sealed class GameSession(
    IAiDecisionService aiDecisionService,
    IAiCrewGenerator crewGenerator,
    IOverseerMessageInterpreter messageInterpreter,
    OllamaRuntimeDiagnostics? runtimeDiagnostics = null)
    : StationSession(messageInterpreter, FacilitySeeder.CreateDefault())
{
    private readonly IAiDecisionService _aiDecisionService = aiDecisionService;
    private readonly IAiCrewGenerator _crewGenerator = crewGenerator;
    private readonly OllamaRuntimeDiagnostics? _runtimeDiagnostics = runtimeDiagnostics;
    private readonly NavigationSystem _navigation = new();

    public override AiRuntimeDiagnosticsSnapshot AiRuntimeDiagnostics =>
        _runtimeDiagnostics?.Snapshot() ?? base.AiRuntimeDiagnostics;

    // The server's decision, crew and message services are the Ollama ones
    // (with a deterministic fallback inside each), so these awaits genuinely
    // wait on the model (owner idea #102).
    protected override string? MessageInterpretationStatus =>
        "AWAITING LLM RESPONSE — READING OVERSEER MESSAGE";

    private int _mindCursor;
    private bool _initialized;

    // Owner rule (2026-09-24): immediate reactions are deterministic and the
    // model's decision takes priority once it arrives. The reflex is the same
    // shared fallback ladder the model falls back to, so it never invents a
    // behaviour the minds could not already choose.
    private readonly RuleBasedAiDecisionService _reflexes = new();

    // Crew acting on a reflex whose model decision has not arrived yet.
    private readonly HashSet<Guid> _awaitingModelAfterReflex = [];

    // (person, hazard room) pairs already given a reflex, so a model that
    // overrides a reflex is not overruled again while the same fire burns.
    private readonly HashSet<(Guid NpcId, string RoomId)> _reflexedHazards = [];

    public override async Task InitializeAsync(
        CancellationToken cancellationToken = default)
    {
        if (_initialized)
        {
            return;
        }

        var scenario = ScenarioCatalog.SecureContinuity;
        var (crew, robots) = await CreateCrewForScenarioAsync(scenario, cancellationToken);
        State = FacilitySeeder.CreateDefault(
            crew,
            stationConstraints: RosterCompositionRules.ConstraintsFor(scenario, crew.Count),
            robotCount: robots);
        _initialized = true;
    }

    private async Task<(IReadOnlyList<Npc> Crew, int RobotCount)> CreateCrewForScenarioAsync(
        ScenarioDefinition scenario,
        CancellationToken cancellationToken)
    {
        // A fresh roster's crew and robot counts come from the uniform roster
        // contract. A continuing campaign keeps its surviving crew, but every
        // new station still gets its own robot count.
        var composition = RosterCompositionRules.Sample(Random.Shared.Next());
        var continuingCrew = CampaignProgressionSystem.CreateCrewForScenario(Campaign, scenario);

        IReadOnlyList<Npc> baseCrew;
        if (continuingCrew is not null)
        {
            baseCrew = continuingCrew;
        }
        else
        {
            var generated = await AwaitWithProcessingStatusAsync(
                "AWAITING LLM RESPONSE — GENERATING CREW",
                () => _crewGenerator.GenerateAsync(cancellationToken));
            baseCrew = CrewRosterScalingSystem.FitToSize(
                generated,
                scenario.Id,
                composition.CrewCount);
        }

        return (PrisonerRosterSystem.Compose(baseCrew, scenario), composition.RobotCount);
    }

    public override async Task ResetAsync(
        CancellationToken cancellationToken = default)
    {
        PauseClock();
        ResetMindQueues();
        Campaign = new CampaignState();
        var scenario = ScenarioCatalog.SecureContinuity;
        var (crew, robots) = await CreateCrewForScenarioAsync(scenario, cancellationToken);
        State = FacilitySeeder.CreateDefault(
            crew,
            stationConstraints: RosterCompositionRules.ConstraintsFor(scenario, crew.Count),
            robotCount: robots);
        _initialized = true;
    }

    public override async Task RegenerateStationAsync(
        int? seed = null,
        CancellationToken cancellationToken = default)
    {
        PauseClock();
        ResetMindQueues();

        var scenario = State.Scenario ?? ScenarioCatalog.SecureContinuity;
        var (crew, robots) = await CreateCrewForScenarioAsync(scenario, cancellationToken);
        State = FacilitySeeder.CreateDefault(
            crew,
            stationSeed: seed,
            stationConstraints: RosterCompositionRules.ConstraintsFor(scenario, crew.Count),
            robotCount: robots);
        ScenarioCatalog.Apply(State, scenario);
        CampaignProgressionSystem.ApplyCarryOver(Campaign, State);
        Campaign.CurrentScenarioId = scenario.Id;
        _initialized = true;
    }

    public override async Task RestoreCampaignAsync(
        CampaignState campaign,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(campaign);

        PauseClock();
        ResetMindQueues();

        if (!CampaignProgressionSystem.CanAutoRestoreCampaign(campaign))
        {
            Campaign = new CampaignState();
            var freshScenario = ScenarioCatalog.SecureContinuity;
            var (freshCrew, freshRobots) = await CreateCrewForScenarioAsync(freshScenario, cancellationToken);
            State = FacilitySeeder.CreateDefault(
                freshCrew,
                stationConstraints: RosterCompositionRules.ConstraintsFor(freshScenario, freshCrew.Count),
                robotCount: freshRobots);
            State.EventLog.Insert(
                0,
                "T+00:00: Previous campaign could not continue because no living crew remained; a fresh assignment was started.");
            _initialized = true;
            return;
        }

        Campaign = campaign;

        var next = CampaignProgressionSystem.NextScenario(Campaign);
        var last = Campaign.MissionHistory.LastOrDefault();
        var scenario = next
            ?? (last is null ? null : ScenarioCatalog.Find(last.ScenarioId))
            ?? throw new InvalidOperationException(
                "Campaign state does not identify a valid scenario roster policy.");

        var (crew, robots) = await CreateCrewForScenarioAsync(scenario, cancellationToken);
        State = FacilitySeeder.CreateDefault(
            crew,
            stationConstraints: RosterCompositionRules.ConstraintsFor(scenario, crew.Count),
            robotCount: robots);
        ScenarioCatalog.Apply(State, scenario);

        if (next is null)
        {
            State.ScenarioStatus = last?.Outcome ?? ScenarioStatus.Won;
            State.ScenarioOutcome = Campaign.Ending?.Summary
                ?? "All campaign assignments are recorded. Awaiting final Overseer decision.";
        }

        CampaignProgressionSystem.ApplyCarryOver(Campaign, State);
        Campaign.CurrentScenarioId = scenario.Id;
        _initialized = true;
    }

    /// <summary>
    /// Starts only the next unlocked campaign assignment on a fresh station.
    /// Arbitrary scenario selection is intentionally rejected by the campaign
    /// layer instead of relying on UI controls for progression integrity.
    /// </summary>
    public override async Task LoadScenarioAsync(
        string scenarioId,
        CancellationToken cancellationToken = default)
    {
        PauseClock();
        ResetMindQueues();
        CampaignProgressionSystem.CaptureCompletedMission(Campaign, State);

        if (!CampaignProgressionSystem.CanStartScenario(Campaign, scenarioId))
        {
            Log($"DIRECTIVE PACKAGE {scenarioId} is locked by campaign progression.");
            return;
        }

        var scenario = ScenarioCatalog.Find(scenarioId);
        if (scenario is null)
        {
            return;
        }

        var (crew, robots) = await CreateCrewForScenarioAsync(scenario, cancellationToken);
        State = FacilitySeeder.CreateDefault(
            crew,
            stationConstraints: RosterCompositionRules.ConstraintsFor(scenario, crew.Count),
            robotCount: robots);
        ScenarioCatalog.Apply(State, scenario);
        CampaignProgressionSystem.ApplyCarryOver(Campaign, State);
        Campaign.CurrentScenarioId = scenario.Id;
        _initialized = true;

        Log($"DIRECTIVE PACKAGE LOADED — {scenario.Title}.");
    }

    /// <inheritdoc />
    public override async Task LoadStandaloneScenarioAsync(
        string scenarioId,
        CancellationToken cancellationToken = default)
    {
        PauseClock();
        ResetMindQueues();

        var scenario = ScenarioCatalog.StandaloneAssignments.FirstOrDefault(candidate =>
            candidate.Id.Equals(scenarioId, StringComparison.OrdinalIgnoreCase));

        if (scenario is null)
        {
            Log($"SPECIAL ASSIGNMENT {scenarioId} is not a recognised standalone package.");
            return;
        }

        var (crew, robots) = await CreateCrewForScenarioAsync(scenario, cancellationToken);
        State = FacilitySeeder.CreateDefault(
            crew,
            stationConstraints: RosterCompositionRules.ConstraintsFor(scenario, crew.Count),
            robotCount: robots);
        ScenarioCatalog.Apply(State, scenario);
        _initialized = true;

        Log($"SPECIAL ASSIGNMENT LOADED — {scenario.Title}.");
    }

    protected override Task ThinkAsync(CancellationToken cancellationToken) =>
        ThinkIfDueAsync(cancellationToken);

    private async Task ThinkIfDueAsync(CancellationToken cancellationToken)
    {
        var living = State.Crew
            .Where(npc =>
                npc.IsAlive
                && !npc.IsContainmentBreachInProgress)
            .OrderBy(npc => npc.Name)
            .ToList();

        if (living.Count == 0)
        {
            return;
        }

        // Environmental danger is allowed to interrupt the normal cognition
        // cadence instead of leaving somebody committed to a 24-minute-old
        // routine while their compartment becomes unsafe. A compartment
        // draining toward a breach through an open hatch beside this person
        // counts too, before its pressure crosses the danger line. Everyone
        // in it reacts at once through a deterministic reflex; the model is
        // then asked, one mind per tick, and its decision replaces the reflex.
        var vacuumDepths = EnvironmentSystem.FindVacuumDepths(State);
        ApplyHazardReflexes(living, vacuumDepths);

        var emergencyNpc = living
            .Where(npc =>
            {
                var room = State.Facility.Rooms[npc.CurrentRoomId];

                // A reflex answered the hazard for now; the model still owes
                // this person a decision while they remain in it.
                if (_awaitingModelAfterReflex.Contains(npc.Id)
                    && (CrewEnvironmentSafety.IsDangerous(room)
                        || vacuumDepths.ContainsKey(room.Id)))
                {
                    return true;
                }

                if (npc.IsPresent
                    && vacuumDepths.Count > 0
                    && DecompressionContainmentRules.FindHatchTowardBreach(
                        State,
                        npc,
                        vacuumDepths) is { } hatch)
                {
                    // Ollama may weigh the open hatch and choose something
                    // else; respect a fresh decision instead of re-asking
                    // every tick until it says CloseDoor.
                    var decidedRecently = npc.Intent is { Urgency: >= 85 }
                        && State.Elapsed - npc.LastThoughtAt < TimeSpan.FromMinutes(2);

                    return !DecompressionContainmentRules.IsAlreadyClosing(npc, hatch)
                        && !decidedRecently;
                }

                return CrewEnvironmentSafety.IsDangerous(room)
                    && !IsAlreadyEscapingToSaferRoom(npc, room);
            })
            // Crew acting on a reflex have not been heard by the model yet;
            // anyone it already answered is asked again after them.
            .OrderByDescending(npc => _awaitingModelAfterReflex.Contains(npc.Id))
            .ThenByDescending(npc =>
                CrewEnvironmentSafety.RiskScore(
                    State.Facility.Rooms[npc.CurrentRoomId]))
            .ThenBy(npc => npc.Name)
            .FirstOrDefault();

        if (emergencyNpc is not null)
        {
            emergencyNpc.Intent = null;
            emergencyNpc.Movement = null;
            emergencyNpc.RoutineUntil = TimeSpan.Zero;

            await ThinkForNpcAsync(
                emergencyNpc,
                emergency: true,
                cancellationToken);

            return;
        }

        var eventNpc = living
            .Where(npc =>
            {
                var freshFireObservation = HasFreshFireObservation(npc);
                var freshFireAlarm = HasFreshFireAlarm(npc);
                var awaitingModel = _awaitingModelAfterReflex.Contains(npc.Id);

                // These are information updates, not deterministic decisions.
                // Only the local model runtime gets this extra wake-up; the
                // static fallback keeps its established decision cadence.
                return (npc.NeedsMindReconsideration
                        || freshFireObservation
                        || freshFireAlarm
                        || awaitingModel)
                    && (npc.Intent is null
                        || npc.Intent.Urgency < 85
                        || npc.Hunger >= 72
                        || npc.Fatigue >= 86
                        || freshFireObservation
                        || freshFireAlarm
                        || awaitingModel);
            })
            .OrderByDescending(npc =>
                npc.MissingPersonConcerns.Values.Any(concern =>
                    concern.Stage == MissingPersonConcernStage.Escalated))
            // Someone acting on a reflex is owed the model's decision before a
            // colleague who has already had one is asked again.
            .ThenByDescending(npc => _awaitingModelAfterReflex.Contains(npc.Id))
            .ThenBy(npc => npc.Name)
            .FirstOrDefault();

        if (eventNpc is not null)
        {
            eventNpc.Intent = null;
            eventNpc.Movement = null;
            eventNpc.RoutineUntil = TimeSpan.Zero;

            await ThinkForNpcAsync(
                eventNpc,
                emergency: eventNpc.MissingPersonConcerns.Count > 0,
                cancellationToken);

            eventNpc.NeedsMindReconsideration = false;
            return;
        }

        var minute = (int)Math.Floor(State.Elapsed.TotalMinutes);

        // One ordinary mind every four simulated minutes. Emergency danger
        // bypasses this cadence above.
        if (minute <= 0 || minute % 4 != 0)
        {
            return;
        }

        // A busy round-robin member must not consume the entire model
        // cadence slot. With small rosters the old pick-then-return logic made
        // the first round of Ollama calls land by ~T+20, then later slots were
        // repeatedly wasted on crew who still had intents even while somebody
        // else was idle. Scan deterministically for the next idle mind instead.
        var npc = MindCadenceRules.NextIdleMind(living, ref _mindCursor);
        if (npc is null)
        {
            return;
        }

        await ThinkForNpcAsync(
            npc,
            emergency: false,
            cancellationToken);
    }

    private async Task ThinkForNpcAsync(
        Npc npc,
        bool emergency,
        CancellationToken cancellationToken)
    {
        _awaitingModelAfterReflex.Remove(npc.Id);

        var intent = await AwaitWithProcessingStatusAsync(
            $"AWAITING LLM RESPONSE — {npc.Name.ToUpperInvariant()} IS DECIDING",
            () => _aiDecisionService.DecideAsync(
                npc,
                State,
                cancellationToken));

        npc.Intent = intent;
        npc.MindMode = intent.Source;
        npc.LastThought = intent.Reason;
        npc.LastThoughtAt = State.Elapsed;
        // Owner idea #85: an in-character line from cognition, when given,
        // replaces the functional goal in the bubble; the goal still drives
        // everything else.
        npc.Bubble = new NpcBubble(
            intent.BubbleText ?? intent.Goal,
            emergency ? NpcBubbleKind.Alert : NpcBubbleKind.Thought,
            State.Elapsed,
            State.Elapsed + TimeSpan.FromMinutes(emergency ? 4 : 3));

        AudioCueSystem.Emit(
            State,
            emergency ? AudioCueKind.Warning : AudioCueKind.Thought,
            npc.Id.ToString(),
            npc.CurrentRoomId);

        // A note of one's own plan is low-value context; at urgency-scaled
        // importance it crowded real experiences out of the prompt.
        npc.Memories.Add(new Memory(
            $"I decided to: {intent.Goal}",
            State.Elapsed,
            0.25));

        Log(
            $"{npc.Name} forms an intention [{intent.Source}]: {intent.Goal}");
    }

    /// <summary>
    /// Owner rule (2026-09-24, #106): a person who meets a hazard reacts at
    /// once through the deterministic model-citizen ladder instead of standing
    /// still until their model turn, which only one mind gets per tick. It
    /// covers someone who sees a fire or hears a FIRE ALARM, is asked to
    /// reconsider while a fire burns, stands in a dangerous room, or stands
    /// beside the open hatch of a compartment draining toward a breach. The
    /// reflex is adopted only when the ladder answers that hazard: fighting the
    /// fire, shutting the hatch toward the breach, or its dangerous-room
    /// response. The person stays queued for the model, whose decision replaces
    /// the reflex when it arrives and is not overruled again while the same
    /// hazard lasts.
    /// </summary>
    private void ApplyHazardReflexes(
        IReadOnlyList<Npc> living,
        IReadOnlyDictionary<string, int> vacuumDepths)
    {
        _reflexedHazards.RemoveWhere(entry =>
            !State.Facility.Rooms.TryGetValue(entry.RoomId, out var room)
            || !IsHazardRoom(room, vacuumDepths));
        _awaitingModelAfterReflex.RemoveWhere(id =>
            living.All(npc => npc.Id != id));

        if (!State.Facility.Rooms.Values.Any(room => IsHazardRoom(room, vacuumDepths)))
        {
            return;
        }

        foreach (var npc in living)
        {
            if (!npc.IsPresent
                || _awaitingModelAfterReflex.Contains(npc.Id)
                || npc.Intent is { Action: ActionKind.FightFire })
            {
                continue;
            }

            var currentRoom = State.Facility.Rooms[npc.CurrentRoomId];
            var inDanger = CrewEnvironmentSafety.IsDangerous(currentRoom);
            var breachHatch = vacuumDepths.Count > 0
                ? DecompressionContainmentRules.FindHatchTowardBreach(State, npc, vacuumDepths)
                : null;

            if (breachHatch is not null
                    ? DecompressionContainmentRules.IsAlreadyClosing(npc, breachHatch)
                    : inDanger && IsAlreadyEscapingToSaferRoom(npc, currentRoom))
            {
                continue;
            }

            var fireNews = State.Facility.Rooms.Values.Any(room => room.FireIntensity > 0)
                && (npc.NeedsMindReconsideration
                    || HasFreshFireObservation(npc)
                    || HasFreshFireAlarm(npc));

            if (!fireNews && !inDanger && breachHatch is null)
            {
                continue;
            }

            var reflex = _reflexes
                .DecideAsync(npc, State, CancellationToken.None)
                .GetAwaiter()
                .GetResult();
            string hazardRoomId;

            if (reflex is { Action: ActionKind.FightFire, TargetId: { } fireRoomId })
            {
                hazardRoomId = fireRoomId;
            }
            else if (breachHatch is not null
                && reflex is { Action: ActionKind.CloseDoor, TargetId: { } hatchId }
                && hatchId.Equals(breachHatch.Id, StringComparison.OrdinalIgnoreCase))
            {
                hazardRoomId = currentRoom.Id;
            }
            else if (inDanger)
            {
                hazardRoomId = currentRoom.Id;
            }
            else
            {
                continue;
            }

            if (!_reflexedHazards.Add((npc.Id, hazardRoomId)))
            {
                continue;
            }

            npc.Intent = reflex with { Source = ReflexSource };
            npc.MindMode = ReflexSource;
            npc.Movement = null;
            npc.RoutineUntil = TimeSpan.Zero;
            npc.Bubble = new NpcBubble(
                reflex.Goal,
                NpcBubbleKind.Alert,
                State.Elapsed,
                State.Elapsed + TimeSpan.FromMinutes(2));
            _awaitingModelAfterReflex.Add(npc.Id);

            Log($"{npc.Name} reacts at once [{ReflexSource}]: {reflex.Goal}");
        }
    }

    private static bool IsHazardRoom(
        Room room,
        IReadOnlyDictionary<string, int> vacuumDepths) =>
        room.FireIntensity > 0
        || CrewEnvironmentSafety.IsDangerous(room)
        || vacuumDepths.ContainsKey(room.Id);

    private void ResetMindQueues()
    {
        _mindCursor = 0;
        _awaitingModelAfterReflex.Clear();
        _reflexedHazards.Clear();
    }

    /// <summary>Intent/mind source for a deterministic reflex awaiting the model.</summary>
    public const string ReflexSource = "Reflex";

    private bool HasFreshFireObservation(Npc npc)
    {
        var currentRoom = State.Facility.Rooms[npc.CurrentRoomId];
        return currentRoom.FireIntensity > 0
            && npc.Memories.Any(memory =>
                memory.ObservedFireRoomId?.Equals(
                    currentRoom.Id,
                    StringComparison.OrdinalIgnoreCase) == true
                && memory.OccurredAt > npc.LastThoughtAt);
    }

    private static bool HasFreshFireAlarm(Npc npc) =>
        npc.ReceivedMessages.FirstOrDefault() is { Claim: OverseerClaimKind.FireAlarm } latestAlarm
        && npc.LastThoughtAt <= latestAlarm.SentAt;

    private bool IsAlreadyEscapingToSaferRoom(Npc npc, Room currentRoom)
    {
        if (npc.Intent is { Action: ActionKind.ForceDoor }
            && npc.CurrentAction.Kind == ActionKind.ForceDoor)
        {
            return true;
        }

        if (npc.Intent is not { Action: ActionKind.Move, TargetId: { } targetId }
            || !State.Facility.Rooms.TryGetValue(targetId, out var targetRoom))
        {
            return false;
        }

        if (CrewEnvironmentSafety.RiskScore(targetRoom)
            >= CrewEnvironmentSafety.RiskScore(currentRoom))
        {
            return false;
        }

        return _navigation.FindPathForCrew(
            State,
            npc,
            currentRoom.Id,
            targetRoom.Id).Count >= 2;
    }
}
