<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Overseer.AI/Overseer.AI.csproj" />
    <ProjectReference Include="../Overseer.Domain/Overseer.Domain.csproj" />
    <ProjectReference Include="../Overseer.Simulation/Overseer.Simulation.csproj" />
    <ProjectReference Include="../Overseer.Persistence/Overseer.Persistence.csproj" />
  </ItemGroup>

</Project>
