using Overseer.Domain;

namespace Overseer.Simulation;

/// <summary>
/// Persistent physical blood evidence generated by real health loss. Evidence
/// is observer-specific until noticed and remains in the world until a capable
/// crew member or friendly maintenance robot physically cleans it.
/// </summary>
public sealed class MedicalEvidenceSystem
{
    public void Tick(GameState state)
    {
        ArgumentNullException.ThrowIfNull(state);

        EmitBlood(state);
        NoticeBlood(state);
        CleanBlood(state);
    }

    private static void EmitBlood(GameState state)
    {
        foreach (var npc in state.Crew.Where(npc => npc.IsPresent))
        {
            var healthLoss = npc.LastHealthSnapshot - npc.Health;
            var shouldEmit = npc.Health < 90
                && healthLoss >= 1
                && (npc.LastBloodEvidenceAt is null
                    || state.Elapsed - npc.LastBloodEvidenceAt >= TimeSpan.FromMinutes(2));

            if (shouldEmit)
            {
                var id = $"blood:{npc.Id:N}:{state.Elapsed.Ticks}";
                state.BloodEvidence.Add(new BloodEvidence(
                    id,
                    npc.Id,
                    npc.CurrentRoomId,
                    npc.PositionX,
                    npc.PositionY,
                    Math.Clamp(healthLoss / 25, .15, 1),
                    state.Elapsed));
                npc.LastBloodEvidenceAt = state.Elapsed;
            }

            npc.LastHealthSnapshot = npc.Health;
        }
    }

    private static void NoticeBlood(GameState state)
    {
        foreach (var observer in state.Crew.Where(npc => npc.IsAlive && npc.IsPresent))
        {
            foreach (var evidence in state.BloodEvidence)
            {
                if (observer.ObservedBloodEvidenceIds.Contains(evidence.Id)
                    || !PerceptionSystem.CanSeeBlood(state, observer, evidence))
                    continue;

                observer.ObservedBloodEvidenceIds.Add(evidence.Id);
                observer.NeedsMindReconsideration = true;
                StatLogSystem.Set(state, observer, CrewStat.Fear, Math.Clamp(observer.Fear + (4 * evidence.Severity), 0, 100), "saw blood");
                StatLogSystem.Set(state, observer, CrewStat.Stress, Math.Clamp(observer.Stress + (3 * evidence.Severity), 0, 100), "saw blood");

                var source = state.Crew.FirstOrDefault(npc => npc.Id == evidence.SourceNpcId);
                observer.Memories.Add(new Memory(
                    source is null
                        ? "I found blood evidence in the compartment."
                        : $"I found blood left by {source.Name}.",
                    state.Elapsed,
                    .62));
            }
        }
    }

    private static void CleanBlood(GameState state)
    {
        foreach (var cleaner in state.Crew.Where(npc =>
                     npc.IsAlive
                     && npc.IsPresent
                     && npc.CurrentAction.Kind == ActionKind.CleanBlood))
        {
            var evidence = state.BloodEvidence
                .Where(item => item.RoomId.Equals(cleaner.CurrentRoomId, StringComparison.OrdinalIgnoreCase))
                .OrderBy(item => Distance(cleaner.PositionX, cleaner.PositionY, item.X, item.Y))
                .FirstOrDefault();

            if (evidence is not null && Distance(cleaner.PositionX, cleaner.PositionY, evidence.X, evidence.Y) <= 16)
            {
                state.BloodEvidence.Remove(evidence);
                cleaner.CurrentAction = new NpcAction(ActionKind.Idle, null, "Blood evidence cleaned.");
                Log(state, $"{cleaner.Name} cleans blood evidence.");
            }
        }

        foreach (var robot in state.Robots.Where(robot =>
                     robot.IsOperational
                     && robot.Policy == RobotPolicy.Friendly))
        {
            var evidence = state.BloodEvidence
                .Where(item => item.RoomId.Equals(robot.CurrentRoomId, StringComparison.OrdinalIgnoreCase))
                .OrderBy(item => Distance(robot.PositionX, robot.PositionY, item.X, item.Y))
                .FirstOrDefault();

            if (evidence is null
                || robot.ActionCompletesAt is not null
                || (!robot.CurrentTask.Contains("inspection", StringComparison.OrdinalIgnoreCase)
                    && !robot.CurrentTask.Contains("patrol", StringComparison.OrdinalIgnoreCase)
                    && !robot.CurrentTask.Contains("Awaiting", StringComparison.OrdinalIgnoreCase)))
                continue;

            state.BloodEvidence.Remove(evidence);
            robot.CurrentTask = "Cleaned blood evidence.";
            Log(state, $"{robot.Name} cleans blood evidence.");
        }
    }

    private static double Distance(double ax, double ay, double bx, double by)
    {
        var dx = ax - bx;
        var dy = ay - by;
        return Math.Sqrt((dx * dx) + (dy * dy));
    }

    private static void Log(GameState state, string message) =>
        state.EventLog.Insert(0, $"T+{state.Elapsed:hh\\:mm}: {message}");
}
